# Generated by Django 6.0.3 on 2026-03-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='is_purchase',
            new_name='is_purchased',
        ),
        migrations.AlterField(
            model_name='seat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.session'),
        ),
    ]
